#mysql
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ChatRoom?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC&useSSL=true
    username: root
    password: 123456
  servlet:
    multipart:
      max-file-size: 100MB
  rabbitmq:
    publisher-confirm-type: correlated   #到达交换机 confirm回调
    publisher-returns: true      #消息没到达队列的return回调
    port: 15723
    virtual-host: /
    host: localhost
    username: guest
    password: guest
    listener:
      simple:
        acknowledge-mode: manual  #等待消费者回复，然后才会手动确认，mq才会把消息移到ack中
    # 开启发送确认机制




mybatis:
  type-aliases-package: com.example.front_back.model             #实体类路径
  mapper-locations: classpath:com.example.front_back.mapper/*.xml        #mapper映射文件的路径
  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl    #控制台打印sql语句
    map-underscore-to-camel-case: true  #下划线转驼峰
server:
  port: 9000
